# Generated by Django 4.1.13 on 2024-10-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult_appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalappointments',
            name='appointment_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalappointments',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalappointments',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
