# Generated by Django 4.1.13 on 2024-10-17 23:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consult_appointments', '0002_alter_medicalappointments_appointment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalappointments',
            name='appointment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalappointments',
            name='appointment_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='medicalappointments',
            name='doctor_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalappointments',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
