# Generated by Django 4.1.13 on 2024-10-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult_appointments', '0003_medicalappointments_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalappointments',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
