# Generated by Django 4.1.13 on 2024-10-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult_appointments', '0004_medicalappointments_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalappointments',
            name='available',
            field=models.BooleanField(),
        ),
    ]
