# Generated by Django 4.1.13 on 2024-10-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult_appointments', '0008_rename_patient_medicalappointments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalappointments',
            name='municipality',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalappointments',
            name='specialty',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
    ]
